version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hackney
    versions:
    - 1.17.0
    - 1.17.1
    - 1.17.2
    - 1.17.3
  - dependency-name: credo
    versions:
    - 1.5.4
